apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentinel
resources:
  - ../../base
  - data-plane.yaml
secretGenerator:
  - name: sentinel-secrets
    envs:
      - secrets.env
    options:
      disableNameSuffixHash: true
patches:
  - path: config-patch.yaml
images:
  - name: sentinel/api
    newName: sentinel/api
    newTag: local
  - name: sentinel/ingestion
    newTag: local
  - name: sentinel/detection
    newTag: local
  - name: sentinel/incident
    newTag: local
  - name: sentinel/ai
    newTag: local
  - name: sentinel/remediation
    newTag: local
  - name: sentinel/web
    newTag: local
